### ISSUE TITLE
PoS: Checkout fails fetching balances

### ISSUE THREAD

**Issue by faberto** [nimiq/hub#517] opened 2023-10-20 12:51 UTC
When using the HUB Api Library it gets stuck at "Updating balances"

<img src="https://github.com/nimiq/hub/assets/29856726/7d4e7978-3f06-48e7-bd0a-827ba4e9589e" width="150">

Code to reproduce:
https://jsfiddle.net/dseqvr12/1/

**Comment by Albermonte** [comment] 2023-10-23 14:23
There was an error with the last deployment, it's already fixed now.

Can you check again? From my side everything is working as expected

**Comment by faberto** [comment] 2023-10-24 05:46
Still the same.
https://jsfiddle.net/8yLbwva4/

**Comment by Albermonte** [comment] 2023-10-24 23:31
Seems like if you have 0 balance it's working, but it's stuck in loading if you have more than 0.
I was not able to reproduce it locally, so no idea right now where's the issue. I'll forward it to the front team.

**Comment by sisou** [comment] 2023-10-25 05:01
@Albermonte this is specifically about the POS Hub. There's a race condition in the WASM client when fetching balances in the consensus-established listener. Sometimes it works, sometimes it fails.

**Comment by sisou** [comment] 2023-11-13 14:20
I'm trying to reproduce to debug, but for me the balances _always_ load. However, when selecting an address to pay, it does nothing. Looking into it, and into the other, too.

**Comment by sisou** [comment] 2023-11-13 14:41
Fixed by ac5a5713455299da8a8e9620370d9d023b401ec2.

The problem wasn't actually the balances (that was a red herring), but a missing network hight, which just silently prevented the address from being selected and the user forwarded to signing.

**Closed by sisou** 2023-11-13 14:41 UTC
